-----------------------------------------------------------------
#   Coursera - Practical Machine Learning Final
-----------------------------------------------------------------

## Preparation
```{r}
packages <- c("caret", "rattle", "rpart", "rpart.plot", "randomForest", 
              "repmis", "e1071")

## Install Necessary Library
# for(package in packages) {
#   install.packages(package)
# }

## Load Library
for(package in packages) {
  library(package, character.only = T)
}
```


## Loading Data from Local
```{r}
training <- read.csv("pml-training.csv", na.strings = c("NA", ""))
testing <- read.csv("pml-testing.csv", na.strings = c("NA", ""))
```

## Data Cleansing
```{r}
training <- training[, colSums(is.na(training)) == 0]
testing <- testing[, colSums(is.na(testing)) == 0]

trainData <- training[, -c(1:7)]
testData <- testing[, -c(1:7)]
```

```{r}
set.seed(1000) 
inTrain <- createDataPartition(trainData$classe, p = 0.7, list = FALSE)
train <- trainData[inTrain, ]
valid <- trainData[-inTrain, ]
```


## Use RandomForests to Predict
```{r}
fitRf <- train(classe ~ ., data = train, method = "rf", trControl = control)
print(fitRf, digits = 4)
# predict outcomes using validation set
predictRf <- predict(fitRf, valid)
# Show prediction result
confRf <- confusionMatrix(valid$classe, predictRf)


accuracyRf <- confRf$overall[1]
```
The performance is
> accuracyRf <- confRf$overall[1]
 Accuracy 
0.9940527 

Then we use the algorithm to predict for quiz
```{r}
predict(fitRf, testData)
```
